apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/lautou/cert-manager
    path: argocd
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - preserveResourcesOnDeletion=true
