apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
    openshift.io/node-selector: "node-role.kubernetes.io/infra="
    scheduler.alpha.kubernetes.io/defaultTolerations: >-
      [{"operator": "Exists", "key":
      "node-role.kubernetes.io/infra"}]
  name: cert-manager
  labels:
    openshift.io/cluster-monitoring: "true"

